### ISSUE TITLE
What's the status of this package?

### ISSUE THREAD

**Issue by maelle** [usa-npn/rnpn#26]
I saw this package was updated on CRAN and noticed there was no GitHub release, but it actually seems this repo is not the actual source? I'm a bit lost. :-) (not an urgent question)

**Comment by ricardobarroslourenco** [comment]
Same question. @npnlee85 can you update this? (not urgent, but hopefully getting an answer)

**Comment by ricardobarroslourenco** [comment]
It seems that there is a more recent fork: https://github.com/usa-npn/rnpn 
@alyssarosemartin can you give a situation on the differences between the packages on ropensci and usa-npn repos?

**Comment by alyssarosemartin** [comment]
Yes - apologies for the delayed response - I became the maintainer last fall  - the latest version/active codebase is on usa-npn  (https://github.com/usa-npn/rnpn). Lee left me a note that we should check in w Scott Chamberlain about how often to unify the two versions. More details from Lee below. Thanks!

"Something that does require some explanation is the lineage to the codebase. This project was originally started by Scott Chamberlain of ROpenSci. That repo lives at https://github.com/ropensci/rnpn

Originally I did some directly on that project but it was generally unmaintained. Eventually, when I needed to work on it, I copied that repo at
https://github.com/usa-npn/rnpn-old

Eventually I wanted to bring all my changes back to ropensci but it wasn’t possible because the repo was cloned and not forked. Thus, the official location began. Ropensci version of the package was forked, my changes were merged in, and now you can work on the usa-npn/rnpn project and make pull requests back to ropensci."

**Comment by maelle** [comment]
@alyssarosemartin (and Lee) Thank you for your answer! 

In that case wouldn't it make sense to not refer to this repository in the DESCRIPTION file, and we'd archive the ropensci repo + no longer list it as an rOpenSci package?

You could still submit it for peer-review at rOpenSci https://devguide.ropensci.org/authors-guide.html (not all peer-reviewed packages have to be transferred to our org).

**Comment by maelle** [comment]
I also meant to link to our curation policy regarding "legacy-acquired packages" https://devguide.ropensci.org/curationpolicy.html#legacy-acquired-packages :smile_cat:

**Comment by ricardobarroslourenco** [comment]
> @alyssarosemartin (and Lee) Thank you for your answer!
> 
> In that case wouldn't it make sense to not refer to this repository in the DESCRIPTION file, and we'd archive the ropensci repo + no longer list it as an rOpenSci package?
> 
> You could still submit it for peer-review at rOpenSci https://devguide.ropensci.org/authors-guide.html (not all peer-reviewed packages have to be transferred to our org).

Yeah, clarifying it on the description would be great (In my case, I'm a new user of it, and it would make it clearer).

**Comment by alyssarosemartin** [comment]
To close the loop here - Maëlle and I transferred the package from ropensci to usa-npn, so it's now no longer forked to usa-npn. The actively maintained version of the package is now this one here (usa-npn/npn). Hopefully now won't be confusing!
